backend:
  name: git-gateway
  branch: main
media_library:
  name: uploadcare
  config:
    publicKey: a2ddae113b0813f64a20
collections:
  - name: 'students'
    label: 'Students'
    label_singular: 'Student'
    folder: '2025/students'
    create: true
    slug: '{{student_name}}'
    preview_path: '2025/{{slug}}'
    view_filters:
      - label: 'Applied Context'
        field: 'context'
        pattern: 'Applied Context'
      - label: 'Autonomous Context'
        field: 'context'
        pattern: 'Autonomous Context'
      - label: 'Digital Context'
        field: 'context'
        pattern: 'Digital Context'
      - label: 'Jewelry Context'
        field: 'context'
        pattern: 'Jewelry Context'
      - label: 'Socio-Political Context'
        field: 'context'
        pattern: 'Socio-Political Context'
    fields:
      - { label: 'Student name', name: 'student_name', widget: 'string' }
      - { label: 'Master project title', name: 'project_title', widget: 'string' }
      - {
          label: 'Context',
          name: 'context',
          widget: 'select',
          options: ['Autonomous Context', 'Applied Context', 'Digital Context', 'Socio-Political Context', 'Jewelry Context']
        }
      - { label: 'Academic year', name: 'year', widget: 'select', options: ['2024—2025'], default: '2024—2025' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: true,
          required: false,
          options:
            [
              'audio',
              'ceramic',
              'clay',
              'digital',
              'ink',
              'installation',
              'metal',
              'paint',
              'paper',
              'performance',
              'photography',
              'screenprinting',
              'sculpture',
              'silver',
              'textile',
              'video'
            ]
        }
      - { label: 'Main image', name: 'main_image', widget: 'image' }
      - {
          label: 'Thumbnail image',
          name: 'thumb_image',
          widget: 'image',
          hint: "Please use a square thumbnail. If you don't provide a thumbnail, the main image will be used.",
          required: false
        }
      - { label: 'Bio', name: 'bio', widget: 'text', hint: 'Describe yourself and your work', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Describe your project' }
      - {
          label: 'Images',
          name: 'images',
          widget: 'image',
          label_singular: 'image',
          required: false,
          media_library: { config: { multiple: true } }
        }
      - {
          label: 'Social links',
          name: 'social_links',
          widget: 'list',
          hint: 'add links to your Social Media, Portfolio, ...',
          label_singular: 'link',
          field: { label: Url, name: url, widget: string }
        }
